# Generated by Django 3.1.4 on 2022-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default='kjk', max_length=100),
            preserve_default=False,
        ),
    ]
