# Generated by Django 3.1.4 on 2022-10-20 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img_produto')),
                ('favorito', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('preco', models.FloatField()),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_utm_alteracao', models.DateField(auto_now=True)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
