# Generated by Django 3.1.4 on 2022-10-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
