# Generated by Django 3.1.4 on 2022-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='img_produto'),
            preserve_default=False,
        ),
    ]
