# Generated by Django 3.1.4 on 2022-10-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('produto', '0007_fav'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fav',
            new_name='Favorito',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='favorito',
        ),
    ]
