# Generated by Django 3.1.4 on 2022-11-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_atributo_produto_detalhe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto_detalhe',
            name='atributo',
        ),
        migrations.RemoveField(
            model_name='produto_detalhe',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.DeleteModel(
            name='Produto_detalhe',
        ),
    ]
