# Generated by Django 2.2.5 on 2022-12-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_produto_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='usuarios',
        ),
    ]
