# Generated by Django 3.1.4 on 2022-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img_produto')),
                ('favorito', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('marca', models.CharField(max_length=80)),
                ('preco', models.FloatField()),
                ('cor', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
