# Generated by Django 3.1.4 on 2022-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto'},
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
