# Generated by Django 3.1.4 on 2022-10-20 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221020_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_utm_alteracao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
