# Generated by Django 2.2.5 on 2022-12-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0008_auto_20221107_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data Emissão')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
    ]
